name: abybaby_it
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  list_wheel_scroll_view_nls: ^0.0.3
  smooth_page_indicator: ^1.1.0
  type_text: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/music/
    - assets/pic/